name: curvenote push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: curvenote push
      uses: curvenote/push-to-curvenote@main
      with:
        path: notes_202101.md
        project: Team Notes
        article: Notes from Jan 2021
        team: curvenote
      env:
        CURVENOTE_TOKEN: ${{ secrets.CURVENOTE_TOKEN }}
