name: curvenote push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: curvenote push
      uses: iinan/docs-blog-template@main
      with:
        path: my-first-post.md
        article: Notes from Jan 2021
      env:
        CURVENOTE_TOKEN: ${{ secrets.CURVENOTE_TOKEN }}
